# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs


jobs:

  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build application
          command: |
            ls
            cd scrybe_frontend
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker build -t badmusanu/hng-task4-frontend .
            docker push badmusanu/hng-task4-frontend
            cd ../backend/app
            docker build -t badmusanu/hng-task4-frontend .
            docker push badmusanu/hng-task4-frontend
  deploy:
      machine:
        enabled: true
      steps:
        - add_ssh_keys:
            fingerprints:
              - "58:b8:5d:b4:73:42:f7:4f:c7:0e:c1:c5:7a:02:a4:7d"
        - checkout
        - run:
            name: Deploy over SSH
            command: ssh $SSH_USER@$SSH_HOST "cd customersupport.web; sudo docker-compose stop; sudo 
docker-compose rm -f; sudo docker-compose pull; sudo docker-compose up -d";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
