"""first migration

Revision ID: 474f4a3334aa
Revises: 74ca96f5a306
Create Date: 2022-12-26 15:24:18.320130

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '474f4a3334aa'
down_revision = '74ca96f5a306'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FreeTrial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.String(length=255), nullable=True),
    sa.Column('transcript_status', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FreeTrial_id'), 'FreeTrial', ['id'], unique=False)
    op.create_index(op.f('ix_FreeTrial_transcript_id'), 'FreeTrial', ['transcript_id'], unique=False)
    op.drop_index('ix_FreeTrial_id', table_name='freetrial')
    op.drop_index('ix_FreeTrial_transcript_id', table_name='freetrial')
    op.drop_table('freetrial')
    op.add_column('jobs', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_column('jobs', 'job_id')
    op.create_table('freetrial',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('transcript_status', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_FreeTrial_transcript_id', 'freetrial', ['transcript_id'], unique=False)
    op.create_index('ix_FreeTrial_id', 'freetrial', ['id'], unique=False)
    op.drop_index(op.f('ix_FreeTrial_transcript_id'), table_name='FreeTrial')
    op.drop_index(op.f('ix_FreeTrial_id'), table_name='FreeTrial')
    op.drop_table('FreeTrial')
    # ### end Alembic commands ###
