"""first migration

Revision ID: 74ca96f5a306
Revises: 
Create Date: 2022-12-25 14:02:49.385396

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '74ca96f5a306'
down_revision = None
branch_labels = #None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FreeTrial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.String(length=255), nullable=True),
    sa.Column('transcript_status', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FreeTrial_id'), 'FreeTrial', ['id'], unique=False)
    op.create_index(op.f('ix_FreeTrial_transcript_id'), 'FreeTrial', ['transcript_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=255), nullable=True),
    sa.Column('time_left', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_plan'), 'companies', ['plan'], unique=False)
    op.create_index(op.f('ix_companies_time_left'), 'companies', ['time_left'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_id'), 'newsletter_subscribers', ['id'], unique=False)
    op.create_table('uploaded_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_jobs_audio_url'), 'uploaded_jobs', ['audio_url'], unique=False)
    op.create_index(op.f('ix_uploaded_jobs_id'), 'uploaded_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_jobs_job_id'), 'uploaded_jobs', ['job_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('aud_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_aud_id'), 'agents', ['aud_id'], unique=False)
    op.create_index(op.f('ix_agents_first_name'), 'agents', ['first_name'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_last_name'), 'agents', ['last_name'], unique=False)
    op.create_index(op.f('ix_agents_location'), 'agents', ['location'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.TEXT(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_logo_url', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('transcript', sa.TEXT(), nullable=True),
    sa.Column('positivity_score', sa.Float(), nullable=True),
    sa.Column('negativity_score', sa.Float(), nullable=True),
    sa.Column('neutrality_score', sa.Float(), nullable=True),
    sa.Column('overall_sentiment', sa.Enum('Positive', 'Negative', 'Neutral'), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_id'), 'analysis', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_negativity_score'), 'analysis', ['negativity_score'], unique=False)
    op.create_index(op.f('ix_analysis_neutrality_score'), 'analysis', ['neutrality_score'], unique=False)
    op.create_index(op.f('ix_analysis_overall_sentiment'), 'analysis', ['overall_sentiment'], unique=False)
    op.create_index(op.f('ix_analysis_positivity_score'), 'analysis', ['positivity_score'], unique=False)
    op.create_index(op.f('ix_analysis_timestamp'), 'analysis', ['timestamp'], unique=False)
    op.create_table('audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.TEXT(), nullable=True),
    sa.Column('filename', sa.TEXT(), nullable=True),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=255), nullable=True),
    sa.Column('transcript', sa.TEXT(), nullable=True),
    sa.Column('positivity_score', sa.Float(), nullable=True),
    sa.Column('negativity_score', sa.Float(), nullable=True),
    sa.Column('neutrality_score', sa.Float(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('overall_sentiment', sa.Enum('Positive', 'Negative', 'Neutral'), nullable=True),
    sa.Column('most_positive_sentences', sa.JSON(), nullable=True),
    sa.Column('most_negative_sentences', sa.JSON(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('agent_firstname', sa.String(length=255), nullable=True),
    sa.Column('agent_lastname', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audios_agent_firstname'), 'audios', ['agent_firstname'], unique=False)
    op.create_index(op.f('ix_audios_agent_lastname'), 'audios', ['agent_lastname'], unique=False)
    op.create_index(op.f('ix_audios_average_score'), 'audios', ['average_score'], unique=False)
    op.create_index(op.f('ix_audios_duration'), 'audios', ['duration'], unique=False)
    op.create_index(op.f('ix_audios_id'), 'audios', ['id'], unique=False)
    op.create_index(op.f('ix_audios_job_id'), 'audios', ['job_id'], unique=False)
    op.create_index(op.f('ix_audios_negativity_score'), 'audios', ['negativity_score'], unique=False)
    op.create_index(op.f('ix_audios_neutrality_score'), 'audios', ['neutrality_score'], unique=False)
    op.create_index(op.f('ix_audios_overall_sentiment'), 'audios', ['overall_sentiment'], unique=False)
    op.create_index(op.f('ix_audios_positivity_score'), 'audios', ['positivity_score'], unique=False)
    op.create_index(op.f('ix_audios_size'), 'audios', ['size'], unique=False)
    op.create_index(op.f('ix_audios_timestamp'), 'audios', ['timestamp'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentiment_result', sa.Enum('Positive', 'Negative', 'Neutral'), nullable=True),
    sa.Column('audio_name', sa.String(length=255), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_agent_name'), 'history', ['agent_name'], unique=False)
    op.create_index(op.f('ix_history_audio_name'), 'history', ['audio_name'], unique=False)
    op.create_index(op.f('ix_history_date_uploaded'), 'history', ['date_uploaded'], unique=False)
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    op.create_index(op.f('ix_history_sentiment_result'), 'history', ['sentiment_result'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('job_status', sa.TEXT(), nullable=True),
    sa.Column('audio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_timestamp'), 'jobs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_timestamp'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_history_sentiment_result'), table_name='history')
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_index(op.f('ix_history_date_uploaded'), table_name='history')
    op.drop_index(op.f('ix_history_audio_name'), table_name='history')
    op.drop_index(op.f('ix_history_agent_name'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_audios_timestamp'), table_name='audios')
    op.drop_index(op.f('ix_audios_size'), table_name='audios')
    op.drop_index(op.f('ix_audios_positivity_score'), table_name='audios')
    op.drop_index(op.f('ix_audios_overall_sentiment'), table_name='audios')
    op.drop_index(op.f('ix_audios_neutrality_score'), table_name='audios')
    op.drop_index(op.f('ix_audios_negativity_score'), table_name='audios')
    op.drop_index(op.f('ix_audios_job_id'), table_name='audios')
    op.drop_index(op.f('ix_audios_id'), table_name='audios')
    op.drop_index(op.f('ix_audios_duration'), table_name='audios')
    op.drop_index(op.f('ix_audios_average_score'), table_name='audios')
    op.drop_index(op.f('ix_audios_agent_lastname'), table_name='audios')
    op.drop_index(op.f('ix_audios_agent_firstname'), table_name='audios')
    op.drop_table('audios')
    op.drop_index(op.f('ix_analysis_timestamp'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_positivity_score'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_overall_sentiment'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_neutrality_score'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_negativity_score'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_id'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_agents_location'), table_name='agents')
    op.drop_index(op.f('ix_agents_last_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_first_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_aud_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_uploaded_jobs_job_id'), table_name='uploaded_jobs')
    op.drop_index(op.f('ix_uploaded_jobs_id'), table_name='uploaded_jobs')
    op.drop_index(op.f('ix_uploaded_jobs_audio_url'), table_name='uploaded_jobs')
    op.drop_table('uploaded_jobs')
    op.drop_index(op.f('ix_newsletter_subscribers_id'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_companies_time_left'), table_name='companies')
    op.drop_index(op.f('ix_companies_plan'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_FreeTrial_transcript_id'), table_name='FreeTrial')
    op.drop_index(op.f('ix_FreeTrial_id'), table_name='FreeTrial')
    op.drop_table('FreeTrial')
    # ### end Alembic commands ###
