name: Main Testing

on:
  push:
    branches: [ "main" ]

jobs:
  
  build_and_push_to_registry:

    # name: Build and push Docker Frontend image to Docker Hub
    # if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scrybe_frontend

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}          
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
      
      - name: docker build, tag and push
        run: |
          docker build -t vicdam/scrybefrontend:${{ steps.commit.outputs.short }} .
          docker push vicdam/scrybefrontend:${{ steps.commit.outputs.short }}

      - name: docker build, tag and push
        run: |
          cd ../backend/app
          docker build -t vicdam/scrybebackend:${{ steps.commit.outputs.short }} .
          docker push vicdam/scrybebackend:${{ steps.commit.outputs.short }}             


  Deploy: 
    needs: [ build_and_push_to_registry ]
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout master
        uses: actions/checkout@master
        
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1       

      - name: Pull from GitHub
        uses: appleboy/ssh-action@master

        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          script: |
            COMPOSE_OPTIONS="-e IMAGE_TAG=${{ steps.commit.outputs.short }}" docker-compose stop
            COMPOSE_OPTIONS="-e IMAGE_TAG=${{ steps.commit.outputs.short }}" docker-compose rm -f
            COMPOSE_OPTIONS="-e IMAGE_TAG=${{ steps.commit.outputs.short }}" docker-compose pull   
            COMPOSE_OPTIONS="-e IMAGE_TAG=${{ steps.commit.outputs.short }}" docker-compose up -d             
            


        
